### ISSUE TITLE
跪求跟完善的使用文档

### ISSUE THREAD

**Issue by lunaticnotcrazy** [dntzhang/cax#11]
跪求跟完善的使用文档

**Comment by dntzhang** [comment]
还有哪些地方不完善？还需要哪些文档能举例一下吗？我们会很快补齐？

**Comment by lunaticnotcrazy** [comment]
不好意思
可能是我的问题
我简单说下我的情况
我是想在微信小程序平台使用caxjs
然后想让
![image](https://user-images.githubusercontent.com/21071051/42073445-5df21280-7b99-11e8-971d-7b6e4d30ec03.png)
代码
`const stage = new cax.Stage(200, 200, 'myCanvas', this)
    const rect = new cax.Rect(100, 100, {
      fillStyle: 'black'
    })

    rect.originX = 50
    rect.originY = 50 
    rect.x = 100
    rect.y = 100
    rect.rotation = 30

    rect.on('drag', res => {
      rect.x += res.dx
      rect.y += res.dy  
    })

    stage.add(rect)
    stage.update()`
这个rect 移动 添加 touchmove 后 
鼠标移动然而并没用效果
想了半天 应该是事件里 需要更新 于是在事件里 加了
  stage.update()
于是能动了
但是效果并不是很好 模拟器中 元素会卡顿
这不是重点 真机居然 不动 我是andorid 测定 ios 并没有测
不知道是不是 我的 姿势不对
然后 就没有 然后了

**Comment by dntzhang** [comment]
使用最新的cax.js 替代你 cax 目录下的 index.js

**Comment by lunaticnotcrazy** [comment]
好 我试下哈 多谢 辛苦了
