### ISSUE TITLE
工具链接使用问题

### ISSUE THREAD

**Issue by g8up** [dntzhang/cax#2]
http://kmdjs.github.io/imagesplitter/

drop image 无效，目测 console 有 js 加载失败。

windows7 
chrome 43

**Comment by kmdjs** [comment]
@g8up  多谢反馈。已经修复。你再试试

**Comment by g8up** [comment]
感谢大大的及时回复，最新想熟悉一下这个工具，业余做一些自己的有趣想法。

1.collision 的 Demo 中 js 代码被压缩了，不方便学习：
http://alloyteam.github.io/AlloyRenderingEngine/example/collision.html

2.text 的 Demo 中 canvas 里啥也没显示：
http://alloyteam.github.io/AlloyGameEngine/example/text.html

**Comment by kmdjs** [comment]
@g8up 
0：弹出一二十个是图片被分割的之后的切片
1：已替换成开发版，但是是早期kmdjs build出来的，主要看Main吧
2：已修复。
