### ISSUE TITLE
bitmap用wx的tempfile地址无法显示图片

### ISSUE THREAD

**Issue by luanwulin** [dntzhang/cax#22]
小程序的api里面，drawImage是可以用tempFilePaths的，直接调用也能画出来，但是bitmap没法实现，是需要怎么兼容么？

**Comment by luanwulin** [comment]
知道原因了，是getImageInWx问题，这里面把https和http的图片全都下载了，但是现在的微信临时图片也是http协议的，所以只要过滤一下地址就可以了

**Comment by dntzhang** [comment]
@luanwulin 真机里的临时文件地址不是 https和http，所以这里真机是ok的~
