### ISSUE TITLE
小游戏点击事件绑定后真机点了没反应 

### ISSUE THREAD

**Issue by Systempm** [dntzhang/cax#25]
电脑的模拟器可以 但是到手机这边怎么点都没反应 ，是哪里操作出现了问题吗？

**Comment by Systempm** [comment]
如果有成功运行的代码那就最好了 ，

**Comment by Systempm** [comment]
另外 我想问下， 有直接清空group中内容的方法吗？

**Comment by dntzhang** [comment]
@Systempm empty 方法，直接清空。回头我把方法补在 readme 里面

**Comment by dntzhang** [comment]
@Systempm  tap  事件刚刚试了是ok的。IOS 还是 安卓？

**Comment by Systempm** [comment]
@dntzhang  tap我用也是好用的 ，我想用的是touchstart touchend ，安卓机。

**Comment by dntzhang** [comment]
额。发现了！小游戏的 canvas 的事件没返回 type ！！！

**Comment by dntzhang** [comment]
这里我 fix 一下~~

**Comment by dntzhang** [comment]
@Systempm 修复了。使用 cax v1.1.5 https://github.com/dntzhang/cax/blob/master/packages/cax-wegame/js/libs/cax.js

**Comment by Systempm** [comment]
@dntzhang 大佬辛苦了
