### ISSUE TITLE
微信小游戏cax.Shape找不到

### ISSUE THREAD

**Issue by lzy2002** [dntzhang/cax#29]
![17](https://user-images.githubusercontent.com/15710163/43352318-72632b56-9254-11e8-8924-aaa42473870e.png)
![18](https://user-images.githubusercontent.com/15710163/43352319-74cb3230-9254-11e8-8bf5-b0042cfb3a62.png)
![19](https://user-images.githubusercontent.com/15710163/43352320-776a86ee-9254-11e8-80a8-ff3397cce85e.png)

**Comment by dntzhang** [comment]
已修复，多谢。
