### ISSUE TITLE
微信开发者工具模拟器正常，真机测试出错

### ISSUE THREAD

**Issue by lzy2002** [dntzhang/cax#31]
![_20180729102429](https://user-images.githubusercontent.com/15710163/43362322-01454834-931a-11e8-91e0-6c3a2afae874.jpg)
touchmove或者drag时卡顿，控制台输出如图

**Comment by dntzhang** [comment]
多谢。已改。你拷贝这个使用试试： https://github.com/dntzhang/cax/blob/master/packages/cax-wegame/js/libs/cax.js
