### ISSUE TITLE
Bitmap没有返回imgwidth 与height？

### ISSUE THREAD

**Issue by Systempm** [dntzhang/cax#32]
![1111x](https://user-images.githubusercontent.com/19610596/43672429-2d2df084-97e0-11e8-915f-9c7b2e7e2f72.png)

**Comment by dntzhang** [comment]
看了下代码发现没问题

**Comment by Systempm** [comment]
我要怎么才能知道  bitmap原图的宽和高？

**Comment by dntzhang** [comment]
我看你截图  rect[2] 和 rect[3]  是宽高？

**Comment by Systempm** [comment]
恩 是图片的长宽

**Comment by Systempm** [comment]
我看#23 那个图片里面就有height 和width属性  为什么到我这边就没有   小游戏里的有 但是到小程序中就不能使用了

**Comment by dntzhang** [comment]
小游戏 和 小程序 canvas 有差异

**Comment by Systempm** [comment]
找到了  可能是我下载的weapp 的版本有点老   少了两行代码 补上就好了

**Comment by Systempm** [comment]
用的 v1.0.12
![2222](https://user-images.githubusercontent.com/19610596/43672611-4d090af2-97e4-11e8-9fb5-b6bd75f27615.png)
