### ISSUE TITLE
group.cache 在小程序中无法使用

### ISSUE THREAD

**Issue by songsharp** [dntzhang/cax#38]
if (typeof wx !== 'undefined' && wx.createCanvas) {
      _this.canvas = wx.createCanvas();
    } else {
      _this.canvas = document.createElement('canvas');
    }

小程序中没有wx.createCanvas

**Comment by dntzhang** [comment]
对啊，所以别用啊

**Comment by dntzhang** [comment]
不能用。不过小程序的canvas快要升级了
