### ISSUE TITLE
Web端使用同时引入微信的JS SDK时会产生冲突

### ISSUE THREAD

**Issue by timshinlee** [dntzhang/cax#46]
在web端使用时，如果同时引入了微信的JS SDK(https://res.wx.qq.com/open/js/jweixin-1.3.2.js) 的话，因为cax中包含了wx.createCanvasContext等操作，而JS SDK中另外定义了一个变量wx，导致cax对wx的方法操作会报错，请问可以另外提供一份无wx的cax库，或者有办法在web环境下不调用到wx.createCanvasContext等方法吗？

**Comment by dntzhang** [comment]
啊？修复了？怎么关啦
