### ISSUE TITLE
Loader跨域加载图片失败

### ISSUE THREAD

**Issue by lujq1020** [dntzhang/cax#5]
使用Loader从cdn加载图片资源是提示
`... No 'Access-Control-Allow-Origin' header is present on the requested ...`
加载MP3资源就没问题

**Comment by moscartong** [comment]
是因爲你資源所在的CDN不支持跨域吧，圖片和MP3文件對應的URL貼出來看看？

**Comment by lujq1020** [comment]
`(function(ARE) {
	var Stage = ARE.Stage;
	var Loader = ARE.Loader;
	var ld = new Loader();
	resources = [{
		id: "bg1",
		src: 'http://cdn.73cis.com/itwx/images/llk/bg1.jpg'
	}, {
		id: 'bgm',
		src: 'http://cdn.73cis.com/itwx/sound/bgm1.mp3'
	}];
	ld.loadRes(resources);
	ld.complete(function() {
		alert('all loaded');
	});
})(ARE);`
刚我发现用http://alloyteam.github.io/AlloyGameEngine/are.min.js 这个版本就可以，但是加载mp3时 会报错·Uncaught TypeError: n.handleProgress is not a function·（上几天提过这问题）

然后我用最新版的are.min.js就加载不了

**Comment by kmdjs** [comment]
@lujq1020 
把loader里面的 img.crossOrigin = "Anonymous"; 去掉就可以了~~。已经修复提交了。
多谢反馈~~

**Comment by kmdjs** [comment]
@lujq1020 
把loader里面的 img.crossOrigin = "Anonymous"; 去掉就可以了。已经修复提交了。
