### ISSUE TITLE
小程序下的canvas会有一个黑色的边框，怎么才能去掉

### ISSUE THREAD

**Issue by dark94da** [dntzhang/cax#60]
按照小程序cax的样例写的页面，
   
    const stage = new cax.Stage(200, 200, 'myCanvas', this)
    const rect = new cax.Rect(100, 100, {
      fillStyle: 'black'
    })
    
    rect.originX = 50
    rect.originY = 50
    rect.x = 100
    rect.y = 100
    rect.rotation = 30

    rect.on('tap', () => {
      console.log('tap')
    })

    stage.add(rect)
    stage.update()

canvas周围会出现一个黑色边框， 应该修改什么设置可以取消掉这个边框吗？
![image](https://user-images.githubusercontent.com/25022398/52909100-33285600-32bd-11e9-8b81-ee5b062d8da8.png)

**Comment by dntzhang** [comment]
改下wxml里的样式

**Comment by dark94da** [comment]
看到了，多谢哈！
