### ISSUE TITLE
不支持开放数据域的离屏canvas渲染吗？

### ISSUE THREAD

**Issue by inarol** [dntzhang/cax#65]
rt.

**Comment by dntzhang** [comment]
小程序不支持，不过即将支持。
小游戏和 web 支持

**Comment by inarol** [comment]
@dntzhang 要开发者自己根据环境调用不同的Stage吗？

**Comment by inarol** [comment]
我的问题描述有点泛了，应该是小游戏的开放数据域需要调用`wx.getSharedCanvas()`来创建离屏canvas，这个貌似就没支持吧？

**Comment by dntzhang** [comment]
这个我不知道

**Comment by inarol** [comment]
是的，阅读了https://github.com/dntzhang/cax/blob/51d3d72ddb04117b95ef13806d70f0005ef10b38/packages/cax/src/render/display/stage.js#L15 应该是只处理`wx.createCanvas`创建的离屏canvas

**Comment by inarol** [comment]
离屏canvas

**Comment by inarol** [comment]
@dntzhang hello，我又几点疑问
1. 另外离屏canvas用cax渲染的话，生成一个stage时，会注册一系列全局的touch等事件，其实是冗余的，也会造成性能问题。不知能否让开发者决定该canvas要不要注册事件。
2. [Stage构造函数的参数](https://github.com/dntzhang/cax/blob/master/packages/cax/src/render/display/stage.js#L9)建议设计成Object参数的形式，这样感觉更加灵活点。

**Comment by dntzhang** [comment]
建议开放数据域不用cax，用原生的
