### ISSUE TITLE
ReferenceError: SCALE_RATIO is not defined

### ISSUE THREAD

**Issue by huangjianke** [dntzhang/cax#72]
![image](https://user-images.githubusercontent.com/8692455/57580616-7837df00-74de-11e9-8dd7-a02d4c287ad6.png)

![image](https://user-images.githubusercontent.com/8692455/57580613-6d7d4a00-74de-11e9-8c94-0935187e4ebb.png)

**Comment by huangjianke** [comment]
@dntzhang 请问下，这个问题如何解决

**Comment by dntzhang** [comment]
https://github.com/dntzhang/cax/commit/8264b15a6e9053fff86db4b19f11f921aa3dad62

**Comment by huangjianke** [comment]
看到了，谢谢
