### ISSUE TITLE
开放数据域的canvas怎么添加

### ISSUE THREAD

**Issue by huangjianke** [dntzhang/cax#79]
看issue试过几种方案，好像都不行。。求指导怎么添加开放数据域

**Comment by dntzhang** [comment]
吃完饭，我找下点十消除代码

**Comment by huangjianke** [comment]
@dntzhang 好的，谢谢

**Comment by dntzhang** [comment]
看了下代码，并没有使用 cax api

**Comment by dntzhang** [comment]
```js
const sharedCanvas = wx.getSharedCanvas()
const context = sharedCanvas.getContext('2d')
```
直接用的 context

**Comment by huangjianke** [comment]
@dntzhang 嗯，这个是没问题，我用的也是原生的
但是怎么添加到 主域 的 Stage 里面呢

```javascript
let openDataContext = wx.getOpenDataContext()
let sharedCanvas = openDataContext.canvas
const bitmap = new cax.Bitmap(sharedCanvas)
stage.add(bitmap)
stage.update()
```

![image](https://user-images.githubusercontent.com/8692455/64507969-ae5f6100-d30e-11e9-9532-83b27ddd51d4.png)

**Comment by dntzhang** [comment]
this.sharedCanvas = store.openDataCtx.canvas
        this.sharedCanvas.width = width
        this.sharedCanvas.height = height*3

        this.bmp = new cax.Bitmap(sharedCanvas)
        this.bmp.ignoreHit = true
        this.group.add(this.bmp)

**Comment by huangjianke** [comment]
@dntzhang 微信讨论群可否加一个？

**Comment by dntzhang** [comment]
群人气太低解散了啊

**Comment by huangjianke** [comment]
@dntzhang 目前开发小游戏遇到不少坑。。大佬你的点十消除可以开源下么，想学习下
