### ISSUE TITLE
wx.createcanvas 推断小程序环境

### ISSUE THREAD

**Issue by buhe** [dntzhang/cax#83]
昨天开始，部分 iOS 机型的小程序也会有 wx.createcanvas 方法，模拟器没有。导致 cax 推断为小游戏环境。

**Comment by buhe** [comment]
![08e97e29-2090-4198-a213-1a9776e02a1a](https://user-images.githubusercontent.com/650753/66883245-cc03a280-efff-11e9-840f-5f0c4a0b411c.jpg)

**Comment by buhe** [comment]
![27a38eb7-9baa-408e-917a-6d7575bde0c3](https://user-images.githubusercontent.com/650753/66883352-3a486500-f000-11e9-85e6-6f8e98b19805.jpg)

**Comment by christal1994** [comment]
哈哈哈，我刚要说这个问题，微信的锅咯，暂时引用wx.createCanvasContext判断咯，但是日后也是坑！！！

**Comment by dntzhang** [comment]
使用 cax 1.3.2 ， 已经修复了

**Comment by buhe** [comment]
肝王赞～ 
随便扯两句，我们最近把 cax 的 svg 移植到了 kbone 上面去了。这样可以在 react 里面直接写动态 svg 了，还 polyfill 了一些 bom ，回头整理好了提 pr 给 kbone

**Comment by dntzhang** [comment]
> 肝王赞～
随便扯两句，我们最近把 cax 的 svg 移植到了 kbone 上面去了。这样可以在 react 里面直接写动态 svg 了，还 polyfill 了一些 bom ，回头整理好了提 pr 给 kbone

别忘了
