### ISSUE TITLE
什么时候支持小程序Canvas 2D

### ISSUE THREAD

**Issue by tttl** [dntzhang/cax#94]

**Comment by dntzhang** [comment]
新的api吗

**Comment by tttl** [comment]
> 新的api吗

对 可以解决同级渲染问题。性能上也好很多

**Comment by dntzhang** [comment]
好。我尽快

**Comment by tttl** [comment]
> 好。我尽快

XD 辛苦

**Comment by murongqimiao** [comment]
我这边也有迫切的， 针对小程序canvas 2d的需求， 辛苦问下，可以共建吗？ 主要是cax部分的原始代码，我可以完成canvas 2d的升级。

**Comment by dntzhang** [comment]
@murongqimiao 提一下 pr，我来合并和发版本
