### ISSUE TITLE
单独的 cax 代码库 和 omi 中的 cax 代码库是同步的么？  

### ISSUE THREAD

**Issue by liaobin312716** [dntzhang/cax#95]
看代码和 omi 下的 cax 代码有差异。
只想用 cax 引擎部分， 使用 这个还是使用 omi 中的 cax ??

https://github.com/Tencent/omi/tree/master/packages/cax/cax

**Comment by dntzhang** [comment]
先用omi中的吧，回头会合进来

**Comment by dntzhang** [comment]
omi中的更先进

**Comment by liaobin312716** [comment]
好的
