### ISSUE TITLE
如何给形状绑定事件？

### ISSUE THREAD

**Issue by g8up** [dntzhang/cax#97]
README.md 里只体现了事件名，如何绑定事件？
比如给一个形状绑定 `tap` 事件？

**Comment by dntzhang** [comment]
用 on 绑定，用 off 解除绑定
https://github.com/dntzhang/cax/blob/master/packages/cax/src/render/base/event-dispatcher.js#L38-L44

**Comment by dntzhang** [comment]
https://github.com/dntzhang/cax/commit/0d8c22bf2a5799b12324692ce7bc3ecc55c6a1c5

文档已经补充
